### ISSUE TITLE
Test XCP 

### ISSUE THREAD

**Issue by Trifi883** [sicrisembay/xcp_peak#1]
Hi , im working on xcp project , so im now focused on peak solution , my project is on c , and the hardware tha t i had is pcan , so can you please give me some advices to launch this code , and the steps required to use pcan-xcp , and thank you in advance . 
Best Regards .

**Comment by Trifi883** [comment]
i had an idea about xcp vector so to implement code in my ecu usig peak solution what is the steps required  i had can driver in my project , where i can intiat the xcp ? and to reforme the xcp frame , if you had some screen shots pdf or some useful guide please shared with me on this mail ! : trifibechir62@gmail.com

**Comment by sicrisembay** [comment]
This example is written in C#.  You need to install Visual Studio (I used VS2019).  You just need to open the solution and build.  There should be no issue in the build.  If there's any issue, let me know by opening an issue.

**Comment by sicrisembay** [comment]
oh by the way, this example only supports Address Granularity of word (as I'm using TMS320 DSP from TI) and not byte

**Comment by Trifi883** [comment]
Thank you very much for your response , the concept is different then vector solution , i build succefully the project and to 
 launch this example i need pcan HW  and calculatorbased on "ARM" and only the interface of pcan basic as software  ? 
i choose the slave and master ID  when i do the connect it can't work the interface of upload / download it's blocked ? any idea please ? 
/ Best Regards

**Comment by Trifi883** [comment]
i don't need any stack to inject it in the ECU ?

**Comment by Trifi883** [comment]
can you please give me some screen shots for the steps of connection , if it's available

**Comment by sicrisembay** [comment]
i'm on business travel right now.. will back to you once i'm back

**Comment by sicrisembay** [comment]
OK.  posted some screenshots in the README.
I can't create the detailed steps as it requires much effort.  You can just easily follow the application event handlers (e.g. Button click handlers).  It should not be that difficult.

Sicris
